### ISSUE TITLE
Error running on Blender 3.4.1

### ISSUE THREAD

**Issue by bartonburke** [SapwoodStudio/Transmogrifier#2]
This would be awesome if I can get it running - I am getting the following error:

```
Python: Traceback (most recent call last):
  File "/Users/bdennysturfee/Library/Application Support/Blender/3.4/scripts/addons/Transmogrifier/__init__.py", line 708, in execute
    self.export_selection(context, base_dir)
  File "/Users/bart/Library/Application Support/Blender/3.4/scripts/addons/Transmogrifier/__init__.py", line 1240, in export_selection
    creationflags=subprocess.CREATE_NEW_CONSOLE,
AttributeError: module 'subprocess' has no attribute 'CREATE_NEW_CONSOLE'
```

**Comment by SapwoodStudio** [comment]
@bartonburke, GNU/Linux support has been [added](https://github.com/SapwoodStudio/Transmogrifier/pull/4) to the main branch.
